-- Borrar preguntas existentes
DELETE FROM questions;
DELETE FROM questions_public;

-- Preguntas de CLASIFICACIÓN (quick)
INSERT INTO questions_public (id, pregunta, tipo, opciones, activa) VALUES
-- CLASIFICACIÓN
('ec471ada-8b43-4b7a-9e00-123456789001','¿Cuántos milímetros tiene un metro?','quick','{"A":"100","B":"10.000","C":"1.000","D":"100.000"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789002','Cali es conocida como:','quick','{"A":"La ciudad Luz","B":"La ciudad del pecado","C":"La ciudad de la furia","D":"La sucursal del cielo"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789003','25 * 25 es:','quick','{"A":"625","B":"2525","C":"425","D":"1025"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789004','Bebida típica del Valle del Cauca:','quick','{"A":"Lulada","B":"Tinto","C":"Coca Cola","D":"Cocoa"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789005','¿Cuántos ríos tiene Cali?','quick','{"A":"Uno","B":"Tres","C":"Cinco","D":"Siete"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789006','¿Cuál es el nombre original del parque de las banderas?','quick','{"A":"Parque Olímpico","B":"Parque de la Juventud","C":"Parque Panamericano","D":"Parque del agua"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789007','Lugar turístico de Cali:','quick','{"A":"Las Lajas","B":"San Antonio","C":"El señor de los Milagros","D":"El Paraíso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789008','Famosa Novela de Jorge Isaacs:','quick','{"A":"El coronel no tiene quien le escriba","B":"Café","C":"La María","D":"El Quijote de la Mancha"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789009','Principal puerto de Colombia en el Pacífico:','quick','{"A":"Tumaco","B":"Buenaventura","C":"Turbo","D":"Barranquilla"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789010','Principal aeropuerto del suroccidente colombiano:','quick','{"A":"Santa Ana","B":"Alfonso Bonilla Aragón","C":"Guillermo León Valencia","D":"Antonio Nariño"}'::jsonb,true),

-- MAIN - preguntas de integridad
('ec471ada-8b43-4b7a-9e00-123456789020','Documento que establece los mínimos de integridad que deben regir el actuar de la DIAN.','main','{"A":"Código de buen Gobierno","B":"Filosofía Dian","C":"Diccionario de Competencias Comportamentales","D":"Código de Integridad"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789021','Honestidad, respeto, compromiso, diligencia y justicia son para la DIAN:','main','{"A":"Cinco palabras","B":"Valores","C":"Temas de trabajo","D":"Riesgos"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789022','Se conoce como el compromiso sagrado de la DIAN:','main','{"A":"El respeto por la diferencia","B":"La atención diligente","C":"La transparencia en el servicio","D":"El recaudo de los recursos económicos del país"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789023','¿Cuál es el valor identificado en esta frase? Actúo siempre con fundamento en la verdad','main','{"A":"Honestidad","B":"Compromiso","C":"Justicia","D":"Diligencia"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789024','¿Cuál es el valor identificado en esta frase? Reconozco, valoro y trato de manera digna','main','{"A":"Honestidad","B":"Respeto","C":"Justicia","D":"Diligencia"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789025','¿Cuál es el valor identificado en esta frase? Cumplo con los deberes con destreza','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789026','¿Cuál es el valor identificado en esta frase? Actúo con imparcialidad','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789027','¿Cuál es el valor identificado en esta frase? No le doy trato preferencial','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789028','¿Cuál es el valor identificado en esta frase? Estoy abierto al diálogo','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789029','¿Cuál es el valor identificado en esta frase? Me capacito y practico el autoaprendizaje','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789030','¿Cuál es el valor identificado en esta frase? Honro la promesa de confidencialidad','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789031','¿Cuál es el valor identificado en esta frase? Tomo decisiones informadas y objetivas','main','{"A":"Justicia","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789032','¿Cuál es el valor identificado en esta frase? No favorezco el punto de vista','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789033','¿Cuál es el valor identificado en esta frase? No malgasto ningún recurso público','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789034','¿Cuál es el valor identificado en esta frase? Reconozco y protejo los derechos','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789035','¿Cuál es el valor identificado en esta frase? Uso responsablemente los recursos públicos','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789036','¿Cuál es el valor identificado en esta frase? Tomo decisiones estableciendo mecanismos de diálogo','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789037','¿Cuál es el valor identificado en esta frase? Aseguro la calidad en cada uno de los productos','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789038','¿Cuál es el valor identificado en esta frase? Atiendo con amabilidad, igualdad y equidad','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789039','¿Cuál es el valor identificado en esta frase? No esconde situaciones personales','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789040','¿Cuál es el valor identificado en esta frase? Me aparto del conocimiento','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789041','¿Cuál es el valor identificado en esta frase? Cumplo a cabalidad mis deberes','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789042','¿Cuál es el valor identificado en esta frase? Presto un servicio ágil','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789043','¿Cuál es el valor identificado en esta frase? Expongo con argumentos mi posición','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789044','¿Cuál es el valor identificado en esta frase? Escucho, atiendo y oriento a quien necesite','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789045','¿Cuál es el valor identificado en esta frase? Apoyo y promuevo espacios de participación','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789046','En nuestro código de Integridad el valor aspiracional de providencia se identifica con:','main','{"A":"El oso de anteojos","B":"La Lechuza","C":"El Jaguar","D":"El Colibrí"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789047','En nuestro código de Integridad el valor aspiracional de valentía se identifica con:','main','{"A":"El oso de anteojos","B":"La Lechuza","C":"El Jaguar","D":"El Colibrí"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789048','En nuestro código de Integridad el valor aspiracional de objetividad se identifica con:','main','{"A":"El oso de anteojos","B":"La Lechuza","C":"El Jaguar","D":"El Colibrí"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789049','En nuestro código de Integridad el valor aspiracional de templanza se identifica con:','main','{"A":"El oso de anteojos","B":"La Lechuza","C":"El Jaguar","D":"El Colibrí"}'::jsonb,true);

-- Copiar a questions con columnas correctas (misma ID)
INSERT INTO questions (id, pregunta, tipo, opciones, correcta, activa)
VALUES
('ec471ada-8b43-4b7a-9e00-123456789001','¿Cuántos milímetros tiene un metro?','quick','{"A":"100","B":"10.000","C":"1.000","D":"100.000"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789002','Cali es conocida como:','quick','{"A":"La ciudad Luz","B":"La ciudad del pecado","C":"La ciudad de la furia","D":"La sucursal del cielo"}'::jsonb,'D',true),
('ec471ada-8b43-4b7a-9e00-123456789003','25 * 25 es:','quick','{"A":"625","B":"2525","C":"425","D":"1025"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789004','Bebida típica del Valle del Cauca:','quick','{"A":"Lulada","B":"Tinto","C":"Coca Cola","D":"Cocoa"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789005','¿Cuántos ríos tiene Cali?','quick','{"A":"Uno","B":"Tres","C":"Cinco","D":"Siete"}'::jsonb,'D',true),
('ec471ada-8b43-4b7a-9e00-123456789006','¿Cuál es el nombre original del parque de las banderas?','quick','{"A":"Parque Olímpico","B":"Parque de la Juventud","C":"Parque Panamericano","D":"Parque del agua"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789007','Lugar turístico de Cali:','quick','{"A":"Las Lajas","B":"San Antonio","C":"El señor de los Milagros","D":"El Paraíso"}'::jsonb,'B',true),
('ec471ada-8b43-4b7a-9e00-123456789008','Famosa Novela de Jorge Isaacs:','quick','{"A":"El coronel no tiene quien le escriba","B":"Café","C":"La María","D":"El Quijote de la Mancha"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789009','Principal puerto de Colombia en el Pacífico:','quick','{"A":"Tumaco","B":"Buenaventura","C":"Turbo","D":"Barranquilla"}'::jsonb,'B',true),
('ec471ada-8b43-4b7a-9e00-123456789010','Principal aeropuerto del suroccidente colombiano:','quick','{"A":"Santa Ana","B":"Alfonso Bonilla Aragón","C":"Guillermo León Valencia","D":"Antonio Nariño"}'::jsonb,'B',true),

('ec471ada-8b43-4b7a-9e00-123456789020','Documento que establece los mínimos de integridad que deben regir el actuar de la DIAN.','main','{"A":"Código de buen Gobierno","B":"Filosofía Dian","C":"Diccionario de Competencias Comportamentales","D":"Código de Integridad"}'::jsonb,'D',true),
('ec471ada-8b43-4b7a-9e00-123456789021','Honestidad, respeto, compromiso, diligencia y justicia son para la DIAN:','main','{"A":"Cinco palabras","B":"Valores","C":"Temas de trabajo","D":"Riesgos"}'::jsonb,'B',true),
('ec471ada-8b43-4b7a-9e00-123456789022','Se conoce como el compromiso sagrado de la DIAN:','main','{"A":"El respeto por la diferencia","B":"La atención diligente","C":"La transparencia en el servicio","D":"El recaudo de los recursos económicos del país"}'::jsonb,'D',true),
('ec471ada-8b43-4b7a-9e00-123456789023','¿Cuál es el valor identificado en esta frase? Actúo siempre con fundamento en la verdad','main','{"A":"Honestidad","B":"Compromiso","C":"Justicia","D":"Diligencia"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789024','¿Cuál es el valor identificado en esta frase? Reconozco, valoro y trato de manera digna','main','{"A":"Honestidad","B":"Respeto","C":"Justicia","D":"Diligencia"}'::jsonb,'B',true),
('ec471ada-8b43-4b7a-9e00-123456789025','¿Cuál es el valor identificado en esta frase? Cumplo con los deberes con destreza','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'B',true),
('ec471ada-8b43-4b7a-9e00-123456789026','¿Cuál es el valor identificado en esta frase? Actúo con imparcialidad','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789027','¿Cuál es el valor identificado en esta frase? No le doy trato preferencial','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789028','¿Cuál es el valor identificado en esta frase? Estoy abierto al diálogo','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789029','¿Cuál es el valor identificado en esta frase? Me capacito y practico el autoaprendizaje','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'D',true),
('ec471ada-8b43-4b7a-9e00-123456789030','¿Cuál es el valor identificado en esta frase? Honro la promesa de confidencialidad','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789031','¿Cuál es el valor identificado en esta frase? Tomo decisiones informadas y objetivas','main','{"A":"Justicia","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789032','¿Cuál es el valor identificado en esta frase? No favorezco el punto de vista','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789033','¿Cuál es el valor identificado en esta frase? No malgasto ningún recurso público','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'B',true),
('ec471ada-8b43-4b7a-9e00-123456789034','¿Cuál es el valor identificado en esta frase? Reconozco y protejo los derechos','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789035','¿Cuál es el valor identificado en esta frase? Uso responsablemente los recursos públicos','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'B',true),
('ec471ada-8b43-4b7a-9e00-123456789036','¿Cuál es el valor identificado en esta frase? Tomo decisiones estableciendo mecanismos de diálogo','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789037','¿Cuál es el valor identificado en esta frase? Aseguro la calidad en cada uno de los productos','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'B',true),
('ec471ada-8b43-4b7a-9e00-123456789038','¿Cuál es el valor identificado en esta frase? Atiendo con amabilidad, igualdad y equidad','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789039','¿Cuál es el valor identificado en esta frase? No esconde situaciones personales','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789040','¿Cuál es el valor identificado en esta frase? Me aparto del conocimiento','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789041','¿Cuál es el valor identificado en esta frase? Cumplo a cabalidad mis deberes','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789042','¿Cuál es el valor identificado en esta frase? Presto un servicio ágil','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'D',true),
('ec471ada-8b43-4b7a-9e00-123456789043','¿Cuál es el valor identificado en esta frase? Expongo con argumentos mi posición','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,'C',true),
('ec471ada-8b43-4b7a-9e00-123456789044','¿Cuál es el valor identificado en esta frase? Escucho, atiendo y oriento a quien necesite','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'D',true),
('ec471ada-8b43-4b7a-9e00-123456789045','¿Cuál es el valor identificado en esta frase? Apoyo y promuevo espacios de participación','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,'D',true),
('ec471ada-8b43-4b7a-9e00-123456789046','En nuestro código de Integridad el valor aspiracional de providencia se identifica con:','main','{"A":"El oso de anteojos","B":"La Lechuza","C":"El Jaguar","D":"El Colibrí"}'::jsonb,'D',true),
('ec471ada-8b43-4b7a-9e00-123456789047','En nuestro código de Integridad el valor aspiracional de valentía se identifica con:','main','{"A":"El oso de anteojos","B":"La Lechuza","C":"El Jaguar","D":"El Colibrí"}'::jsonb,'A',true),
('ec471ada-8b43-4b7a-9e00-123456789048','En nuestro código de Integridad el valor aspiracional de objetividad se identifica con:','main','{"A":"El oso de anteojos","B":"La Lechuza","C":"El Jaguar","D":"El Colibrí"}'::jsonb,'B',true),
('ec471ada-8b43-4b7a-9e00-123456789049','En nuestro código de Integridad el valor aspiracional de templanza se identifica con:','main','{"A":"El oso de anteojos","B":"La Lechuza","C":"El Jaguar","D":"El Colibrí"}'::jsonb,'C',true)
ON CONFLICT DO NOTHING;

-- Preguntas FALTANTES del documento de Integridad (todas tipo 'main')
-- Estas complementan las ya existentes en el SQL original

INSERT INTO questions (id, pregunta, tipo, opciones, correcta, activa)
VALUES

-- Preguntas sobre VALORES (descripciones completas, distintas a las del SQL original)
('ec471ada-8b43-4b7a-9e00-123456789050',
 '¿Cuál es el valor identificado en esta frase? Soy consciente de la importancia de mi rol como servidor público y estoy en disposición permanente para comprender y resolver las necesidades de las personas',
 'main',
 '{"A":"Honestidad","B":"Respeto","C":"Justicia","D":"Compromiso"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789051',
 '¿Cuál es el valor identificado en esta frase? Cumplo con los deberes, funciones y responsabilidades asignadas a mi cargo de la mejor manera posible, con atención, prontitud, destreza y eficiencia',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,
 'B', true),

('ec471ada-8b43-4b7a-9e00-123456789052',
 '¿Cuál es el valor identificado en esta frase? Actúo con imparcialidad garantizando los derechos de las personas, con equidad, igualdad y sin discriminación',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,
 'C', true),

('ec471ada-8b43-4b7a-9e00-123456789053',
 '¿Cuál es el valor identificado en esta frase? Nunca llego a pensar que mi trabajo como servidor es un "favor" que le hago a la ciudadanía. Es, en cambio, un compromiso y un orgullo',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789054',
 '¿Cuál es el valor identificado en esta frase? Conozco y entiendo en detalle el ordenamiento jurídico que regula mi función y me capacito a conciencia para realizar mi labor con parámetros de excelencia',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'B', true),

('ec471ada-8b43-4b7a-9e00-123456789055',
 '¿Cuál es el valor identificado en esta frase? Nunca permito que odios, simpatías, antipatías, caprichos, presiones o intereses personales interfieran en mi criterio y toma de decisiones',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,
 'C', true),

('ec471ada-8b43-4b7a-9e00-123456789056',
 '¿Cuál es el valor identificado en esta frase? No evado mis funciones y responsabilidades por ningún motivo',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,
 'B', true),

('ec471ada-8b43-4b7a-9e00-123456789057',
 '¿Cuál es el valor identificado en esta frase? Jamás baso mis decisiones en presunciones, estereotipos, o prejuicios',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'C', true),

('ec471ada-8b43-4b7a-9e00-123456789058',
 '¿Cuál es el valor identificado en esta frase? Contribuyo a la generación de un adecuado clima laboral con mi buena actitud en el trabajo y en la relación con los demás',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'C', true),

('ec471ada-8b43-4b7a-9e00-123456789059',
 '¿Cuál es el valor identificado en esta frase? Siempre estoy dispuesto a asumir una posición de empatía, al ponerme en los zapatos de las personas, a entender su contexto y necesidades',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789060',
 '¿Cuál es el valor identificado en esta frase? Tomo decisiones estableciendo mecanismos de diálogo y concertación con las partes involucradas',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,
 'C', true),

('ec471ada-8b43-4b7a-9e00-123456789061',
 '¿Cuál es el valor identificado en esta frase? No promuevo ni ejecuto políticas, programas o medidas que afectan la igualdad y la libertad de las personas',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,
 'C', true),

('ec471ada-8b43-4b7a-9e00-123456789062',
 '¿Cuál es el valor identificado en esta frase? Estoy atento y mantengo una adecuada escucha siempre que interactúo con otras personas, sin permitirme ni permitir distracciones de ningún tipo',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789063',
 '¿Cuál es el valor identificado en esta frase? Cumplo con los tiempos estipulados para el logro de cada obligación laboral. El tiempo de todos es valioso',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,
 'B', true),

('ec471ada-8b43-4b7a-9e00-123456789064',
 '¿Cuál es el valor identificado en esta frase? No soy descuidado con la información a mi cargo, ni con su gestión',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789065',
 '¿Cuál es el valor identificado en esta frase? De ninguna manera me refiero a los otros injuriosa o calumniosamente, ni con ironía, burla, sarcasmo o desdén',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'C', true),

('ec471ada-8b43-4b7a-9e00-123456789066',
 '¿Cuál es el valor identificado en esta frase? No demuestro desinterés en mis actuaciones ante los ciudadanos y ante los demás servidores públicos',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'B', true),

('ec471ada-8b43-4b7a-9e00-123456789067',
 '¿Cuál es el valor identificado en esta frase? Soy proactivo comunicando a tiempo propuestas para mejorar continuamente mi labor y la de mis compañeros de trabajo',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'B', true),

('ec471ada-8b43-4b7a-9e00-123456789068',
 '¿Cuál es el valor identificado en esta frase? No postergo decisiones ni actividades que den solución a problemáticas ciudadanas. Hay situaciones que no se dejan para otro día',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'B', true),

('ec471ada-8b43-4b7a-9e00-123456789069',
 '¿Cuál es el valor identificado en esta frase? Estudio e interiorizo todas las normas relacionadas con la disciplina, empleo público y manejo de bienes, recursos e información que atañen a mi condición',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789070',
 '¿Cuál es el valor identificado en esta frase? Nunca trabajo con una actitud negativa. No es válido afectar mi trabajo por no ponerle ganas y pasión a mis responsabilidades',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789071',
 '¿Cuál es el valor identificado en esta frase? No asumo que mi trabajo como servidor es irrelevante para la sociedad. Jamás ignoro a un ciudadano y sus inquietudes',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789072',
 '¿Cuál es el valor identificado en esta frase? Asumo mi papel como servidor público, entendiendo el valor de los compromisos y responsabilidades que he adquirido frente a la ciudadanía y al país',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789073',
 '¿Cuál es el valor identificado en esta frase? En situaciones extraordinarias, redoblo con generosidad mis esfuerzos para brindar un servicio oportuno, porque entiendo que las circunstancias ameritan un superior empeño',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789074',
 '¿Cuál es el valor identificado en esta frase? Nunca actúo de manera discriminatoria, grosera o hiriente, bajo ninguna circunstancia',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'C', true),

('ec471ada-8b43-4b7a-9e00-123456789075',
 '¿Cuál es el valor identificado en esta frase? No justifico situaciones administrativas o accedo a mejoras laborales con documentos falsos',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789076',
 '¿Cuál es el valor identificado en esta frase? No presto ni facilito mi carné de identificación; no uso la identificación de otro funcionario para simular el registro de ingreso o salida',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789077',
 '¿Cuál es el valor identificado en esta frase? No acepto incentivos, favores, ni ningún otro tipo de beneficio que me ofrezcan personas o grupos interesados en un proceso de toma de decisiones',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789078',
 '¿Cuál es el valor identificado en esta frase? No uso recursos públicos para fines personales relacionados con mi familia, mis estudios y mis pasatiempos',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789079',
 '¿Cuál es el valor identificado en esta frase? Siempre digo la verdad, incluso cuando tengo errores, porque es humano cometerlos, pero no es correcto esconderlos',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789080',
 '¿Cuál es el valor identificado en esta frase? Cuando tengo dudas respecto a la aplicación de mis deberes, busco orientación en las instancias pertinentes. Es válido no saberlo todo y también es válido pedir ayuda',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789081',
 '¿Cuál es el valor identificado en esta frase? Facilito el acceso a la información pública completa, veraz, oportuna y comprensible a través de los medios destinados para ello',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789082',
 '¿Cuál es el valor identificado en esta frase? Denuncio siempre las faltas, delitos o violaciones de derechos de los que tengo conocimiento en el ejercicio de mi cargo',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789083',
 '¿Cuál es el valor identificado en esta frase? Apoyo y promuevo espacios de participación para que los ciudadanos hagan parte de la toma de decisiones que los afectan',
 'main',
 '{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,
 'A', true),

-- Preguntas sobre valores ASPIRACIONALES (enunciados completos)
('ec471ada-8b43-4b7a-9e00-123456789084',
 '"Somos sobrios y enfrentamos con determinación y buen juicio la lucha contra la evasión y el contrabando generando los recursos necesarios para el sostenimiento del Estado social de derecho". Este enunciado identifica el valor aspiracional de:',
 'main',
 '{"A":"Providencia","B":"Valentía","C":"Objetividad","D":"Templanza"}'::jsonb,
 'D', true),

('ec471ada-8b43-4b7a-9e00-123456789085',
 '"Nos anticipamos a las eventualidades que puedan sobrevenir y, ante los reveces, continuamos de forma decidida en el cumplimiento de nuestra misión; cerrar la brecha tributaria y acabar con el contrabando". Este enunciado identifica el valor aspiracional de:',
 'main',
 '{"A":"Providencia","B":"Valentía","C":"Objetividad","D":"Templanza"}'::jsonb,
 'A', true),

('ec471ada-8b43-4b7a-9e00-123456789086',
 '"Luchamos contra las economías criminales para garantizar el imperio de la ley en todos los rincones del país". Este enunciado identifica el valor aspiracional de:',
 'main',
 '{"A":"Providencia","B":"Valentía","C":"Objetividad","D":"Templanza"}'::jsonb,
 'B', true),

('ec471ada-8b43-4b7a-9e00-123456789087',
 '"Cumplimos nuestras funciones basándonos en evidencia rigurosa, sin sesgos para fortalecer la confianza de la ciudadanía en la DIAN y en el Estado". Este enunciado identifica el valor aspiracional de:',
 'main',
 '{"A":"Providencia","B":"Valentía","C":"Objetividad","D":"Templanza"}'::jsonb,
 'C', true)

ON CONFLICT DO NOTHING;


-- Copiar también a questions_public (sin columna 'correcta')
INSERT INTO questions_public (id, pregunta, tipo, opciones, activa)
VALUES
('ec471ada-8b43-4b7a-9e00-123456789050','¿Cuál es el valor identificado en esta frase? Soy consciente de la importancia de mi rol como servidor público y estoy en disposición permanente para comprender y resolver las necesidades de las personas','main','{"A":"Honestidad","B":"Respeto","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789051','¿Cuál es el valor identificado en esta frase? Cumplo con los deberes, funciones y responsabilidades asignadas a mi cargo de la mejor manera posible, con atención, prontitud, destreza y eficiencia','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789052','¿Cuál es el valor identificado en esta frase? Actúo con imparcialidad garantizando los derechos de las personas, con equidad, igualdad y sin discriminación','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789053','¿Cuál es el valor identificado en esta frase? Nunca llego a pensar que mi trabajo como servidor es un "favor" que le hago a la ciudadanía. Es, en cambio, un compromiso y un orgullo','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789054','¿Cuál es el valor identificado en esta frase? Conozco y entiendo en detalle el ordenamiento jurídico que regula mi función y me capacito a conciencia para realizar mi labor con parámetros de excelencia','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789055','¿Cuál es el valor identificado en esta frase? Nunca permito que odios, simpatías, antipatías, caprichos, presiones o intereses personales interfieran en mi criterio y toma de decisiones','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789056','¿Cuál es el valor identificado en esta frase? No evado mis funciones y responsabilidades por ningún motivo','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789057','¿Cuál es el valor identificado en esta frase? Jamás baso mis decisiones en presunciones, estereotipos, o prejuicios','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789058','¿Cuál es el valor identificado en esta frase? Contribuyo a la generación de un adecuado clima laboral con mi buena actitud en el trabajo y en la relación con los demás','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789059','¿Cuál es el valor identificado en esta frase? Siempre estoy dispuesto a asumir una posición de empatía, al ponerme en los zapatos de las personas, a entender su contexto y necesidades','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789060','¿Cuál es el valor identificado en esta frase? Tomo decisiones estableciendo mecanismos de diálogo y concertación con las partes involucradas','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789061','¿Cuál es el valor identificado en esta frase? No promuevo ni ejecuto políticas, programas o medidas que afectan la igualdad y la libertad de las personas','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789062','¿Cuál es el valor identificado en esta frase? Estoy atento y mantengo una adecuada escucha siempre que interactúo con otras personas, sin permitirme ni permitir distracciones de ningún tipo','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789063','¿Cuál es el valor identificado en esta frase? Cumplo con los tiempos estipulados para el logro de cada obligación laboral. El tiempo de todos es valioso','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789064','¿Cuál es el valor identificado en esta frase? No soy descuidado con la información a mi cargo, ni con su gestión','main','{"A":"Honestidad","B":"Diligencia","C":"Justicia","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789065','¿Cuál es el valor identificado en esta frase? De ninguna manera me refiero a los otros injuriosa o calumniosamente, ni con ironía, burla, sarcasmo o desdén','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789066','¿Cuál es el valor identificado en esta frase? No demuestro desinterés en mis actuaciones ante los ciudadanos y ante los demás servidores públicos','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789067','¿Cuál es el valor identificado en esta frase? Soy proactivo comunicando a tiempo propuestas para mejorar continuamente mi labor y la de mis compañeros de trabajo','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789068','¿Cuál es el valor identificado en esta frase? No postergo decisiones ni actividades que den solución a problemáticas ciudadanas. Hay situaciones que no se dejan para otro día','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789069','¿Cuál es el valor identificado en esta frase? Estudio e interiorizo todas las normas relacionadas con la disciplina, empleo público y manejo de bienes, recursos e información que atañen a mi condición','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789070','¿Cuál es el valor identificado en esta frase? Nunca trabajo con una actitud negativa. No es válido afectar mi trabajo por no ponerle ganas y pasión a mis responsabilidades','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789071','¿Cuál es el valor identificado en esta frase? No asumo que mi trabajo como servidor es irrelevante para la sociedad. Jamás ignoro a un ciudadano y sus inquietudes','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789072','¿Cuál es el valor identificado en esta frase? Asumo mi papel como servidor público, entendiendo el valor de los compromisos y responsabilidades que he adquirido frente a la ciudadanía y al país','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789073','¿Cuál es el valor identificado en esta frase? En situaciones extraordinarias, redoblo con generosidad mis esfuerzos para brindar un servicio oportuno, porque entiendo que las circunstancias ameritan un superior empeño','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789074','¿Cuál es el valor identificado en esta frase? Nunca actúo de manera discriminatoria, grosera o hiriente, bajo ninguna circunstancia','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789075','¿Cuál es el valor identificado en esta frase? No justifico situaciones administrativas o accedo a mejoras laborales con documentos falsos','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789076','¿Cuál es el valor identificado en esta frase? No presto ni facilito mi carné de identificación; no uso la identificación de otro funcionario para simular el registro de ingreso o salida','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789077','¿Cuál es el valor identificado en esta frase? No acepto incentivos, favores, ni ningún otro tipo de beneficio que me ofrezcan personas o grupos interesados en un proceso de toma de decisiones','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789078','¿Cuál es el valor identificado en esta frase? No uso recursos públicos para fines personales relacionados con mi familia, mis estudios y mis pasatiempos','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789079','¿Cuál es el valor identificado en esta frase? Siempre digo la verdad, incluso cuando tengo errores, porque es humano cometerlos, pero no es correcto esconderlos','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789080','¿Cuál es el valor identificado en esta frase? Cuando tengo dudas respecto a la aplicación de mis deberes, busco orientación en las instancias pertinentes. Es válido no saberlo todo y también es válido pedir ayuda','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789081','¿Cuál es el valor identificado en esta frase? Facilito el acceso a la información pública completa, veraz, oportuna y comprensible a través de los medios destinados para ello','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789082','¿Cuál es el valor identificado en esta frase? Denuncio siempre las faltas, delitos o violaciones de derechos de los que tengo conocimiento en el ejercicio de mi cargo','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789083','¿Cuál es el valor identificado en esta frase? Apoyo y promuevo espacios de participación para que los ciudadanos hagan parte de la toma de decisiones que los afectan','main','{"A":"Honestidad","B":"Diligencia","C":"Respeto","D":"Compromiso"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789084','"Somos sobrios y enfrentamos con determinación y buen juicio la lucha contra la evasión y el contrabando generando los recursos necesarios para el sostenimiento del Estado social de derecho". Este enunciado identifica el valor aspiracional de:','main','{"A":"Providencia","B":"Valentía","C":"Objetividad","D":"Templanza"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789085','"Nos anticipamos a las eventualidades que puedan sobrevenir y, ante los reveces, continuamos de forma decidida en el cumplimiento de nuestra misión; cerrar la brecha tributaria y acabar con el contrabando". Este enunciado identifica el valor aspiracional de:','main','{"A":"Providencia","B":"Valentía","C":"Objetividad","D":"Templanza"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789086','"Luchamos contra las economías criminales para garantizar el imperio de la ley en todos los rincones del país". Este enunciado identifica el valor aspiracional de:','main','{"A":"Providencia","B":"Valentía","C":"Objetividad","D":"Templanza"}'::jsonb,true),
('ec471ada-8b43-4b7a-9e00-123456789087','"Cumplimos nuestras funciones basándonos en evidencia rigurosa, sin sesgos para fortalecer la confianza de la ciudadanía en la DIAN y en el Estado". Este enunciado identifica el valor aspiracional de:','main','{"A":"Providencia","B":"Valentía","C":"Objetividad","D":"Templanza"}'::jsonb,true)

ON CONFLICT DO NOTHING;